[package]
name = "plonkish_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
hex-literal = "0.4.1"
ctr = { git = "https://github.com/RustCrypto/block-modes", rev = "78fefba5a80f3d788fd8ba7c4483625148f5dc18" }
halo2_curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "v0.4.0", package = "halo2curves", features = [
    "derive_serde",
] }
ff = { version = "0.13.0", features = ["derive"] }
pasta_curves = { version = "0.5.1", features = ["serde"] }
generic-array = { version = "0.14.7", features = ["serde"] }
bitvec = "1.0.1"
itertools = "0.13.0"
num-bigint = "0.4.6"
num-integer = "0.1.46"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
threadpool = "1.8.1"
bincode = "1.3.3"
sha3 = "0.10.8"
blake2b_simd = "1.0.2"
blake2 = { version = "0.10.6" }
poseidon = { git = "https://github.com/han0110/poseidon", branch = "feature/with-spec" }
rand_chacha = { version = "0.3.1", features = ["serde1"] }
# timer
ark-std = { version = "^0.4.0", default-features = false, optional = true }

# parallel
rayon = { version = "1.5.3", optional = true }
subtle = "2.5.0"
# frontend-halo2
halo2_proofs = { git = "https://github.com/han0110/halo2.git", branch = "feature/for-benchmark", optional = true }
plonky2_util = { path = "../plonky2_util" }
crossbeam = "0.8.2"

# plonky3
# p3-air = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/air" }
# p3-field = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/field" }
# p3-matrix = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/matrix" }
# p3-mersenne-31 = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/mersenne-31" }
# p3-util = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/util" }
# p3-baby-bear = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/baby-bear" }
# p3-challenger = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/challenger" }
# p3-circle = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/circle" }
# p3-commit = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/commit" }
# p3-dft = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/dft" }
# p3-fri = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/fri" }
# p3-goldilocks = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/goldilocks" }
# p3-blake3 = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/blake3" }
# p3-keccak = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/keccak" }
# p3-mds = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/mds" }
# p3-merkle-tree = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/merkle-tree" }
# p3-poseidon = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/poseidon" }
# p3-poseidon2 = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/poseidon2" }
# p3-symmetric = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/symmetric" }
# p3-monty-31 = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/monty-31" }
# p3-bn254-fr = { path = "/Users/ahy231/Documents/GitHub/MyPlonky3/bn254-fr" }
p3-air = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-field = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-matrix = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-mersenne-31 = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-util = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-baby-bear = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-challenger = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-circle = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-commit = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-dft = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-fri = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-goldilocks = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-blake3 = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-keccak = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-mds = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-merkle-tree = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-poseidon = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-poseidon2 = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-symmetric = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-monty-31 = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
p3-bn254-fr = { git = "https://github.com/ahy231/Plonky3", rev = "8d2027e421c8d3f8f3b4d0da66f47458801af965" }
serde_json = "1.0"

[dev-dependencies]
paste = "1.0.11"
criterion = "0.4.0"
pprof = { version = "0.11.0", features = ["criterion", "flamegraph"] }
crossbeam = "0.8.2"
[features]
default = ["parallel", "frontend-halo2", "sanity-check"]

timer = ["dep:ark-std", "ark-std?/print-trace", "halo2_proofs?/print-trace"]
parallel = ["dep:rayon"]
frontend-halo2 = ["dep:halo2_proofs"]

benchmark = ["parallel"]
sanity-check = []

[[bench]]
name = "zero_check"
harness = false
required-features = ["benchmark"]
