use crate::{
    pcs::{
        multilinear::additive,
        univariate::{UnivariateKzg, UnivariateKzgCommitment},
        Evaluation, Point, PolynomialCommitmentScheme,
    },
    poly::{
        multilinear::{merge_into, MultilinearPolynomial},
        univariate::UnivariatePolynomial,
        Polynomial,
    },
    util::{
        arithmetic::{squares, Field, MultiMillerLoop},
        chain,
        transcript::{TranscriptRead, TranscriptWrite},
        DeserializeOwned, Itertools, Serialize,
    },
    Error,
};

use rand::RngCore;
use std::{marker::PhantomData, ops::Neg};

#[derive(Clone, Debug)]
pub struct Gemini<Pcs>(PhantomData<Pcs>);

// Implementing the PolynomialCommitmentScheme trait for Gemini<UnivariateKzg<M>>
// The type Gemini<UnivariateKzg<M>> will act as a polynomial commitment scheme.
impl<M> PolynomialCommitmentScheme<M::Scalar> for Gemini<UnivariateKzg<M>>
where
    // M must implement the MultiMillerLoop trait, which provides pairing operations and Miller loops.
    M: MultiMillerLoop,

    // The scalar field of the pairing curve (M::Scalar) must support serialization and deserialization
    // to allow encoding/decoding of scalars for communication or storage.
    M::Scalar: Serialize + DeserializeOwned,

    // The affine representation of the G1 elliptic curve group must also support serialization
    // and deserialization for safe storage and transmission.
    M::G1Affine: Serialize + DeserializeOwned,

    // Similarly, the affine representation of the G2 elliptic curve group must support
    // serialization and deserialization.
    M::G2Affine: Serialize + DeserializeOwned,
{
    // The type for parameters required by the commitment scheme.
    // It is taken from the `UnivariateKzg<M>` implementation of `PolynomialCommitmentScheme<M::Scalar>`.
    type Param = <UnivariateKzg<M> as PolynomialCommitmentScheme<M::Scalar>>::Param;

    // The type for the prover's specific parameters.
    // This is also inherited from the `UnivariateKzg<M>` implementation of the same trait.
    type ProverParam = <UnivariateKzg<M> as PolynomialCommitmentScheme<M::Scalar>>::ProverParam;

    // The type for the verifier's specific parameters.
    // Similarly inherited from the `UnivariateKzg<M>` implementation.
    type VerifierParam = <UnivariateKzg<M> as PolynomialCommitmentScheme<M::Scalar>>::VerifierParam;

    // The type representing the polynomial used in the scheme.
    // Here, it specifies `MultilinearPolynomial<M::Scalar>`, a multilinear polynomial
    // over the scalar field of the pairing curve (M::Scalar).
    type Polynomial = MultilinearPolynomial<M::Scalar>;

    // The type for a commitment to a polynomial.
    // It is inherited from the `UnivariateKzg<M>` implementation of `PolynomialCommitmentScheme`.
    type Commitment = <UnivariateKzg<M> as PolynomialCommitmentScheme<M::Scalar>>::Commitment;

    // The type for a chunked commitment, which might be used for batching or efficient
    // proof generation/verification. Again, inherited from `UnivariateKzg<M>`.
    type CommitmentChunk =
        <UnivariateKzg<M> as PolynomialCommitmentScheme<M::Scalar>>::CommitmentChunk;

    /// Sets up the parameters for the polynomial commitment scheme.
    ///
    /// - `poly_size` is the maximum size of the polynomial(s) that can be committed.
    /// - `batch_size` indicates how many polynomials (or separate statements) you may want to commit to in a batch.
    /// - `rng` is a random number generator used to create cryptographic randomness.
    ///
    /// Returns a `Result` containing the commitment parameters if successful,
    /// or an `Error` if something goes wrong during setup.
    fn setup(poly_size: usize, batch_size: usize, rng: impl RngCore) -> Result<Self::Param, Error> {
        // Delegate the setup logic to the underlying UnivariateKzg<M> scheme.
        // UnivariateKzg's `setup` method will produce the necessary parameters
        // (public keys, secret keys, etc.) for committing to polynomials up to
        // `poly_size` in length and for batching up to `batch_size` polynomials.
        UnivariateKzg::<M>::setup(poly_size, batch_size, rng)
    }

    /// "Trims" the full parameter set (produced by `setup`) to generate separate
    /// parameters for the prover and verifier. Trimming is commonly used to reduce
    /// the parameter size to what's necessary for specific polynomial sizes and batch sizes.
    ///
    /// - `param` is a reference to the full commitment parameters generated by `setup`.
    /// - `poly_size` is the target size (or degree) of polynomials for which you want
    ///   to generate trimmed parameters.
    /// - `batch_size` is how many polynomials you plan to commit or prove in a single batch.
    ///
    /// Returns a tuple `(Self::ProverParam, Self::VerifierParam)`, or an error if trimming fails.
    fn trim(
        param: &Self::Param,
        poly_size: usize,
        batch_size: usize,
    ) -> Result<(Self::ProverParam, Self::VerifierParam), Error> {
        // The underlying KZG-based scheme (UnivariateKzg<M>) provides a trim function that
        // does the heavy lifting. We simply delegate to it here, passing along the full
        // parameters (`param`) plus the desired `poly_size` and `batch_size`.
        UnivariateKzg::<M>::trim(param, poly_size, batch_size)
    }

    /// Commits to a multilinear polynomial (stored as an array of evaluations) using
    /// the prover's parameters (`pp`). This commitment is a binding, hiding reference
    /// to the polynomial.
    ///
    /// # Arguments
    /// * `pp`   - The prover parameters, containing the necessary commitment keys.
    /// * `poly` - The polynomial to commit to, which stores evaluations (or coefficients)
    ///            in a form understood by the underlying KZG scheme.
    ///
    /// # Returns
    /// A `Result` containing the commitment on success, or an error if the polynomial
    /// exceeds the supported degree or any other parameter violation occurs.
    fn commit(pp: &Self::ProverParam, poly: &Self::Polynomial) -> Result<Self::Commitment, Error> {
        // Check if the polynomial's degree is within the bounds supported by the prover parameters.
        // The `pp.degree()` represents the maximum degree supported; `poly.evals().len()` is the
        // polynomial's number of evaluations or coefficients.
        // If the polynomial is too large, return an error.
        if pp.degree() + 1 < poly.evals().len() {
            return Err(Error::InvalidPcsParam(format!(
                "Too large degree of poly to commit (param supports degree up to {} but got {})",
                pp.degree(),
                poly.evals().len()
            )));
        }

        // Delegate the actual commitment calculation to the underlying KZG function, which
        // interprets the polynomial's evaluations (or coefficients) and produces a group element
        // representing the commitment.
        Ok(UnivariateKzg::commit_coeffs(pp, poly.evals()))
    }

    /// Commits to multiple polynomials in a single batch, returning a vector of commitments.
    ///
    /// # Arguments
    /// * `pp`    - The prover parameters, containing the necessary commitment keys.
    /// * `polys` - An iterator (or collection) of references to polynomials that need to be committed.
    ///
    /// # Returns
    /// A `Result` containing a vector of commitments on success. Each commitment corresponds
    /// to one polynomial from the input sequence. Returns an error if any polynomial
    /// fails to commit (e.g., if it exceeds the supported degree).
    fn batch_commit<'a>(
        pp: &Self::ProverParam,
        polys: impl IntoIterator<Item = &'a Self::Polynomial>,
    ) -> Result<Vec<Self::Commitment>, Error> {
        // Convert the incoming collection/iterator into an iterator, then map each polynomial
        // to a call to `Self::commit(pp, poly)`. This transforms each polynomial into a commitment
        // or an error.
        polys
            .into_iter()
            .map(|poly| Self::commit(pp, poly))
            // Collect all results into a `Vec<Self::Commitment>`. If any commitment fails,
            // the entire operation returns an error via `?`-like behavior in `.collect()`.
            .collect()
    }

    // ...

    /// Opens (proves knowledge of) a multilinear polynomial at a specific "point"
    /// (a vector of scalars). The proof is written into the provided transcript.
    ///
    /// # Arguments
    /// - `pp`         : Prover parameters necessary for opening commitments.
    /// - `poly`       : The multilinear polynomial we're opening.
    /// - `comm`       : The commitment corresponding to `poly`.
    /// - `point`      : The evaluation point (x_1, x_2, ..., x_n).
    /// - `eval`       : The claimed evaluation P(x_1, ..., x_n) = eval.
    /// - `transcript` : A mutable reference to a transcript, used for the
    ///                  Fiat-Shamir transform to obtain random challenges.
    ///
    /// # Returns
    /// An `Ok(())` if the opening data has been successfully written into the transcript.
    /// Any errors (e.g., if the polynomial is too large for `pp`) are returned otherwise.
    fn open(
        pp: &Self::ProverParam,
        poly: &Self::Polynomial,
        comm: &Self::Commitment,
        point: &Point<M::Scalar, Self::Polynomial>,
        eval: &M::Scalar,
        transcript: &mut impl TranscriptWrite<Self::CommitmentChunk, M::Scalar>,
    ) -> Result<(), Error> {
        // --------------------------------------------------------------------
        // 1. Check polynomial size against the prover parameters.
        //    If the polynomial's number of evaluations is larger than pp.degree() + 1,
        //    it means the parameters do not support a polynomial of this size.
        // --------------------------------------------------------------------
        let num_vars = point.len(); // number of variables in the multilinear polynomial
        if pp.degree() + 1 < poly.evals().len() {
            return Err(Error::InvalidPcsParam(format!(
                "Too large degree of poly to open (param supports degree up to {} but got {})",
                pp.degree(),
                poly.evals().len()
            )));
        }

        // --------------------------------------------------------------------
        // 2. Optional Sanity Check (compile-time feature flag "sanity-check").
        //    - We re-commit the polynomial and ensure it matches the passed-in commitment.
        //    - We also directly evaluate the polynomial at `point` to confirm `eval`.
        // --------------------------------------------------------------------
        if cfg!(feature = "sanity-check") {
            // Ensure the polynomial's commitment matches `comm`.
            assert_eq!(Self::commit(pp, poly).unwrap().0, comm.0);

            // Ensure the polynomial evaluates to `eval` at `point`.
            assert_eq!(poly.evaluate(point), *eval);
        }

        // --------------------------------------------------------------------
        // 3. Folding the Multilinear Polynomial into a Sequence of Univariate Polynomials.
        //
        //    A multilinear polynomial P(x_1, x_2, ..., x_n) can be "folded" variable
        //    by variable into a univariate polynomial f_i(t) by choosing x_i in {0, 1}
        //    and collapsing the evaluations accordingly.
        //
        //    This step produces a chain of univariate polynomials f_0, f_1, ..., f_{n-1},
        //    leading to a final polynomial f_{n-1} of small degree. The final polynomial's
        //    evaluation at `point[n-1]` matches the claimed `eval`.
        // --------------------------------------------------------------------
        let fs = {
            // We'll accumulate each univariate polynomial in this vector.
            let mut fs = Vec::with_capacity(num_vars);

            // f_0 is the base univariate polynomial built from the original set
            // of evaluations (the raw coefficients or direct evaluation table).
            fs.push(UnivariatePolynomial::new(poly.evals().to_vec()));

            // For each variable x_i (except the last), we build f_{i+1} from f_i
            // by "merging" evaluations. The function `merge_into` typically does
            // something like:
            //     f_{i+1}(t) = f_i(t) with x_i fixed to either 0 or 1,
            // so that the polynomial's dimension in that variable collapses.
            for x_i in &point[..num_vars - 1] {
                // Get the coefficients of the current univariate polynomial f_i.
                let f_i_minus_one = fs.last().unwrap().coeffs();

                // We create space for half as many coefficients because
                // collapsing one variable halves the dimension in that variable.
                let mut f_i = Vec::with_capacity(f_i_minus_one.len() >> 1);

                // The `merge_into` function merges the two "halves" of f_i_minus_one,
                // weighting by x_i for the part where x_i=1.
                // The key step:
                //   merged = eval_0 + x_i * (eval_1 - eval_0)
                //
                // If x_i = 0, merged = eval_0.
                // If x_i = 1, merged = eval_1.
                // Otherwise, this is a linear interpolation in the field F.
                // *t = (*eval_1 - *eval_0) * x_i + *eval_0;
                merge_into(&mut f_i, f_i_minus_one, x_i, 1, 0);

                // Now we store the new univariate polynomial f_i.
                fs.push(UnivariatePolynomial::new(f_i));
            }

            // Optional check for the last polynomial's correctness when "sanity-check"
            // feature is enabled. We ensure the final polynomial f_last can reproduce
            // the expected evaluation at the last variable x_{n-1}.
            if cfg!(feature = "sanity-check") {
                let f_last = fs.last().unwrap();
                let x_last = point.last().unwrap();
                assert_eq!(
                    f_last[0] * (M::Scalar::ONE - x_last) + f_last[1] * x_last,
                    *eval
                );
            }

            fs
        };

        // --------------------------------------------------------------------
        // 4. Commit to the folded univariate polynomials (other than the 0th one,
        //    which corresponds to the original `comm`).
        //
        //    We create a chain of commitments: the first item is the original
        //    polynomial’s commitment `comm`, followed by the commitments to f_1, f_2, ...
        //    returned by `batch_commit_and_write`. The function writes these
        //    commitments into the transcript, which the verifier can reference.
        // --------------------------------------------------------------------
        let comms = chain![
            // Start with the existing multilinear commitment.
            [comm.clone()],
            // Then commit to (and write) the univariate polynomials f_1..f_{n-1}.
            UnivariateKzg::<M>::batch_commit_and_write(pp, &fs[1..], transcript)?
        ]
        .collect_vec();

        // --------------------------------------------------------------------
        // 5. Generate a Fiat-Shamir challenge `beta` from the transcript.
        //    Then compute powers (or squares) of `beta`, applying a negative sign
        //    for half of them, for a total of n+1 points.
        //
        //    We will evaluate the f_i polynomials at these new points for the batch opening.
        // --------------------------------------------------------------------
        let beta = transcript.squeeze_challenge();
        let points = chain![
            [beta],                      // first challenge
            squares(beta).map(Neg::neg)  // squares of beta, each negated
        ]
        .take(num_vars + 1)
        .collect_vec();

        // --------------------------------------------------------------------
        // 6. Gather the evaluations that we'll prove in the final batch_open call.
        //    - This is a chain from:
        //         (0,0) => f_0 evaluated at index=0, point=0
        //         (0,1) => f_0 at index=0, point=1
        //         (1..num_vars).zip(2..) => each f_i at the corresponding challenge index
        //    - Each `Evaluation::new(idx, point, value)` records which polynomial
        //      (idx) is being evaluated, at which "point" (the challenge index),
        //      and the resulting evaluation.
        // --------------------------------------------------------------------
        let evals = chain!([(0, 0), (0, 1)], (1..num_vars).zip(2..))
            .map(|(idx, p_idx)| Evaluation::new(idx, p_idx, fs[idx].evaluate(&points[p_idx])))
            .collect_vec();

        // Write the (claimed) evaluations—except the first one—into the transcript.
        // The verifier will compare these to the actual expansions in its verification step.
        transcript.write_field_elements(evals[1..].iter().map(Evaluation::value))?;

        // --------------------------------------------------------------------
        // 7. Perform the actual batch opening over all univariate polynomials f_i.
        //    This call will generate a single proof (or set of proofs) attesting
        //    that each f_i truly evaluates to `evals[i]` at the specified points.
        //
        //    The proof data is also written into the transcript, which ensures
        //    non-interactive security via the Fiat-Shamir transform.
        // --------------------------------------------------------------------
        UnivariateKzg::<M>::batch_open(pp, &fs, &comms, &points, &evals, transcript)
    }

    /// Opens (proves evaluations for) multiple polynomials simultaneously in a single batch.
    ///
    /// # Arguments
    /// * `pp`        - The prover's parameters (e.g., secret or partially secret data).
    /// * `polys`     - An iterable of references to all the polynomials being opened.
    /// * `comms`     - An iterable of references to the commitments corresponding to those polynomials.
    /// * `points`    - A slice of points at which the polynomials are claimed to be evaluated.
    /// * `evals`     - A slice of `Evaluation` objects, each storing which polynomial was evaluated,
    ///                 at which index, and the claimed value.
    /// * `transcript`- A mutable transcript to record the opening proof data (for a non-interactive proof).
    ///
    /// # Returns
    /// * `Ok(())` on success, meaning the proofs for all polynomials have been written to `transcript`.
    /// * An error if anything goes wrong (e.g., dimension mismatches, invalid parameters).

    fn batch_open<'a>(
        pp: &Self::ProverParam,
        polys: impl IntoIterator<Item = &'a Self::Polynomial>,
        comms: impl IntoIterator<Item = &'a Self::Commitment>,
        points: &[Point<M::Scalar, Self::Polynomial>],
        evals: &[Evaluation<M::Scalar>],
        transcript: &mut impl TranscriptWrite<Self::CommitmentChunk, M::Scalar>,
    ) -> Result<(), Error> {
        let polys = polys.into_iter().collect_vec();
        let comms = comms.into_iter().collect_vec();

        for eval in evals {
            Self::open(
                pp,
                polys[eval.poly()],
                comms[eval.poly()],
                &points[eval.point()],
                &eval.value(),
                transcript,
            )?;
        }
        Ok(())
    }

    /// Reads (deserializes) multiple polynomial commitments from the transcript.
    /// This is typically what a verifier does to reconstruct the commitments from
    /// proof data and proceed with verification.
    ///
    /// # Arguments
    /// * `vp`         - The verifier's parameters (usually a subset of the universal parameters).
    /// * `num_polys`  - How many polynomial commitments we expect to read.
    /// * `transcript` - A transcript reader from which we'll pull the commitments.
    ///
    /// # Returns
    /// * `Ok(Vec<Self::Commitment>)` on success, containing all the deserialized commitments.
    /// * An error if deserialization or transcript reading fails.
    fn read_commitments(
        vp: &Self::VerifierParam,
        num_polys: usize,
        transcript: &mut impl TranscriptRead<Self::CommitmentChunk, M::Scalar>,
    ) -> Result<Vec<Self::Commitment>, Error> {
        // Delegates to `UnivariateKzg::read_commitments`, which knows how to read and
        // reconstruct each commitment from the transcript. We simply forward the call
        // here to reuse the KZG logic.
        UnivariateKzg::read_commitments(vp, num_polys, transcript)
    }

    /// Verifies a single multilinear polynomial evaluation proof.
    ///
    /// # Arguments
    /// * `vp`        - Verifier parameters (e.g., public keys, group generators).
    /// * `comm`      - The commitment to the polynomial claimed by the prover.
    /// * `point`     - The evaluation point (a vector of scalars) for the multilinear polynomial.
    /// * `eval`      - The claimed result of polynomial(point).
    /// * `transcript`- A transcript from which we read the proof data (commitments, challenges, evaluations).
    ///
    /// # Returns
    /// * `Ok(())` if verification succeeds (proof checks out).
    /// * An error if the proof is invalid or if something goes wrong (e.g. out-of-bounds, transcript failure).
    fn verify(
        vp: &Self::VerifierParam,
        comm: &Self::Commitment,
        point: &Point<M::Scalar, Self::Polynomial>,
        eval: &M::Scalar,
        transcript: &mut impl TranscriptRead<Self::CommitmentChunk, M::Scalar>,
    ) -> Result<(), Error> {
        // --------------------------------------------------------------------
        // 1. Determine how many variables the polynomial has by looking at
        //    the length of 'point'. A 3-variable polynomial => point.len()=3, etc.
        // --------------------------------------------------------------------
        let num_vars = point.len();

        // --------------------------------------------------------------------
        // 2. Read the intermediate commitments (for the univariate folds) from
        //    the transcript. We already have the first commitment (comm.0).
        //    Then we read num_vars - 1 more commitments from the transcript
        //    (one for each "fold" after the initial).
        // --------------------------------------------------------------------
        let comms = chain![
            [comm.0],                                   // The original polynomial's commitment.
            transcript.read_commitments(num_vars - 1)?  // The folded polynomial commitments.
        ]
        // Wrap each raw group element in a UnivariateKzgCommitment type.
        .map(UnivariateKzgCommitment)
        .collect_vec();

        // --------------------------------------------------------------------
        // 3. Generate a Fiat-Shamir challenge 'beta' from the transcript.
        //    The transcript approach ensures non-interactive security.
        // --------------------------------------------------------------------
        let beta = transcript.squeeze_challenge();

        // --------------------------------------------------------------------
        // 4. Precompute squares of beta (beta^2, beta^4, ...) as needed.
        //    We only take num_vars squares, because each variable folding
        //    step uses one such challenge power.
        // --------------------------------------------------------------------
        let squares_of_beta = squares(beta).take(num_vars).collect_vec();

        // --------------------------------------------------------------------
        // 5. Read from the transcript the claimed evaluations of the folded polynomials.
        //    Typically, the prover wrote these partial evaluations into the transcript
        //    during the 'open' process.
        // --------------------------------------------------------------------
        let evals = transcript.read_field_elements(num_vars)?;

        // --------------------------------------------------------------------
        // 6. Reconstruct the *very first* polynomial's "folded" evaluation at
        //    index 0 (i.e., the base of the chain), combining everything via
        //    the final expression below. This is a form of inverse folding:
        //
        //    We do a reverse fold:
        //        eval_pos = the known result from the next step,
        //        eval_neg = the next polynomial's partial eval,
        //        x_i      = the variable's coordinate in 'point'.
        //
        //    We combine them with a factor derived from squares_of_beta.
        //    The final result should match 'eval' (the original polynomial's
        //    claimed value at 'point'), if the proof is correct.
        // --------------------------------------------------------------------
        let one = M::Scalar::ONE;
        let two = one.double();

        // eval_0 is computed by iterating from the last variable backwards.
        // 'fold' starts with eval_0 = *eval (the claimed final evaluation),
        // and then merges in each partial evaluation in reverse.
        let eval_0 = evals
            .iter()
            .zip(&squares_of_beta)
            .zip(point)
            .rev() // process from the last variable to the first
            .fold(*eval, |eval_pos, ((eval_neg, square_of_beta), x_i)| {
                // Numerically, we're performing:
                //   eval_0 = [2 * square_of_beta * eval_pos
                //             - ((1 - x_i)*square_of_beta - x_i) * eval_neg]
                //            * ( ((1 - x_i)*square_of_beta + x_i) )^-1
                //
                // This recovers the polynomial evaluation at one step "earlier" in
                // the folding chain. If all commitments and partial evals are correct,
                // we end up with a consistent final eval_0 matching the polynomial's
                // value at the initial folds.
                (two * square_of_beta * eval_pos
                    - ((one - *x_i) * *square_of_beta - *x_i) * *eval_neg)
                    * (((one - *x_i) * *square_of_beta + *x_i).invert().unwrap())
            });

        // --------------------------------------------------------------------
        // 7. Bundle up all evaluations into the expected format for univariate
        //    KZG verification. We produce a list of (polynomial_index, point_index, value).
        //    For each fold index, we have an evaluation. The chain of indexing below
        //    matches how the proofs are generated in 'open'.
        // --------------------------------------------------------------------
        let evals = chain![
            // For f_0: (0,0), (0,1) => these correspond to the first polynomial's partial indices
            (0..1).cartesian_product(0..2).take(2),
            // Then (1..num_vars) => the subsequent folds with indices 2.. in the transcript
            (1..num_vars).zip(2..)
        ]
        .zip(chain![[eval_0], evals]) // pair each index with the relevant evaluation
        .map(|((idx, point_idx), eval)| Evaluation::new(idx, point_idx, eval))
        .collect_vec();

        // --------------------------------------------------------------------
        // 8. Collect the final "points" array for batch verification. The first
        //    element is 'beta'; the subsequent are negative squares of beta.
        //    This is how the proof uses random challenges for each folded polynomial.
        // --------------------------------------------------------------------
        let points = chain![[beta], squares_of_beta.into_iter().map(Neg::neg)].collect_vec();

        // --------------------------------------------------------------------
        // 9. Finally, delegate to UnivariateKzg::<M>::batch_verify, which checks
        //    all the univariate commitments (f_0..f_{n-1} after folding) are
        //    correct at the specified points with the claimed evaluations.
        // --------------------------------------------------------------------
        UnivariateKzg::<M>::batch_verify(vp, &comms, &points, &evals, transcript)
    }

    /// Verifies multiple polynomial commitments (and their evaluations) in one batch.
    ///
    /// # Arguments
    /// * `vp`       - The verifier's parameters.
    /// * `comms`    - An iterator of references to commitments for each polynomial.
    /// * `points`   - A slice of points at which each polynomial is evaluated.
    /// * `evals`    - The claimed evaluations for the polynomials.
    /// * `transcript` - A transcript from which we read the necessary proof data.
    ///
    /// # Returns
    /// * `Ok(())` on success, meaning all polynomials' evaluations have been verified.
    /// * An error if verification fails or an inconsistency is found.
    // fn batch_verify<'a>(
    //     vp: &Self::VerifierParam,
    //     comms: impl IntoIterator<Item = &'a Self::Commitment>,
    //     points: &[Point<M::Scalar, Self::Polynomial>],
    //     evals: &[Evaluation<M::Scalar>],
    //     transcript: &mut impl TranscriptRead<Self::CommitmentChunk, M::Scalar>,
    // ) -> Result<(), Error> {
    //     // Determine how many variables from the first 'point' or default to 0 if no points.
    //     let num_vars = points.first().map(|point| point.len()).unwrap_or_default();

    //     // Collect the commitments into a vector (rather than an iterator).
    //     let comms = comms.into_iter().collect_vec();

    //     // Delegate to `additive::batch_verify`, presumably an internal helper that checks
    //     // multiple polynomial evaluations in an additive or multi-polynomial context.
    //     additive::batch_verify::<_, Self>(vp, num_vars, comms, points, evals, transcript)
    // }

    fn batch_verify<'a>(
        vp: &Self::VerifierParam,
        comms: impl IntoIterator<Item = &'a Self::Commitment>,
        points: &[Point<M::Scalar, Self::Polynomial>],
        evals: &[Evaluation<M::Scalar>],
        transcript: &mut impl TranscriptRead<Self::CommitmentChunk, M::Scalar>,
    ) -> Result<(), Error> {
        let comms = comms.into_iter().collect_vec();
        for eval in evals {
            Self::verify(
                vp,
                comms[eval.poly()],
                &points[eval.point()],
                eval.value(),
                transcript,
            )?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod test {
    use crate::{
        pcs::{
            multilinear::{
                gemini::Gemini,
                test::{run_batch_commit_open_verify, run_commit_open_verify},
            },
            univariate::UnivariateKzg,
        },
        util::transcript::Keccak256Transcript,
    };
    use halo2_curves::bn256::Bn256;

    type Pcs = Gemini<UnivariateKzg<Bn256>>;

    #[test]
    fn commit_open_verify() {
        run_commit_open_verify::<_, Pcs, Keccak256Transcript<_>>();
    }

    #[test]
    fn batch_commit_open_verify() {
        run_batch_commit_open_verify::<_, Pcs, Keccak256Transcript<_>>();
    }
}
