[workspace]
members = ["bench-cli", "benchmark", "plonkish_backend"]

[profile.flamegraph]
inherits = "release"
debug = true
codegen-units = 1

# Remove patch after https://github.com/privacy-scaling-explorations/halo2curves/pull/47 is merged.
[patch."https://github.com/privacy-scaling-explorations/halo2curves"]
halo2_curves = { git = "https://github.com/han0110/halo2curves", branch = "feature/hash-to-curve", package = "halo2curves" }

[workspace.dependencies]
serde = { version = "1.0.152" }
criterion = "0.5.1"
ff = "0.13"
itertools = "0.14.0"
halo2curves = "0.8.0"
num-bigint = { version = "0.4.3", default-features = false }
num-integer = "0.1.46"
num-traits = { version = "0.2.19", default-features = false }
nums = "0.1.0"
rand = "0.8.5"
rayon = "1.7.0"
transpose = "0.2.3"
rand_chacha = "0.3.1"
rand_xoshiro = "0.6.0"
serde_json = "1.0.113"
gcd = "1.0"
hashbrown = "0.14"
tracing = "0.1.37"
tracing-forest = "0.1.6"
tracing-subscriber = "0.3.19"
tiny-keccak = "2.0.2"
blake3 = "1.5.5"
num = "0.4.3"
sha3 = "0.11.0-pre.4"
modinverse = "0.1.1"
zkhash = { git = "https://github.com/HorizenLabs/poseidon2" }
